### ISSUE TITLE
Can you add a license?

### ISSUE THREAD

**Issue by Not-Nik** [16Bitt/virtix#1]
I really like the project and tinkering around with it was really fun, but I wondered if you could add a license so others can use your work. As [this article](https://choosealicense.com/no-permission) explains, unlicensed project sadly can't be used by others without risking to violate copyright law.

**Comment by 16Bitt** [comment]
Absolutely! I haven't touched this in awhile, but I'd be happy to add a
license tomorrow. Any opposition to the code being GPL?

**Comment by Not-Nik** [comment]
GPL indeed has a lot of conditions for usage. Of course, which license to add is up to you, but I'd recommend Apache or MIT. Both don't have copyleft and give users a lot of freedom.

**Comment by 16Bitt** [comment]
[Done!](https://github.com/16Bitt/virtix/blob/master/LICENSE) Closing this issue out.

Thank you for your interest in this project, I'm really happy to see any engagement on this given that it was just a hobby OS I wrote in high school. If you need anything else, please let me know!

**Comment by 16Bitt** [comment]
MIT license has been added!

**Comment by Not-Nik** [comment]
Thank you, very appreciated ^^
